name: CI Pipeline

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          docker --version
          docker build -t todo-app .

      - name: Run tests with Docker
        run: |
          docker run --rm todo-app pytest tests/
          
      - name: Push Docker image (optional)
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag todo-app myusername/todo-app:latest
          docker push myusername/todo-app:latest
