name: CI Pipeline

permissions:
  contents: write  # Permet la modification du dépôt
  packages: write  # Nécessaire pour pousser les images Docker

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  

      - name: Set up Docker
        run: |
          docker --version
          docker build -t todo-app .

      - name: Run tests with Docker
        run: |
          docker run --rm todo-app pytest tests/

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag todo-app myusername/todo-app:latest
          docker push myusername/todo-app:latest

      - name: Create merge commit
        if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'dev' && success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout main
          git merge dev --no-ff -m "Auto-merge after successful tests"
          git push origin main
